### ISSUE TITLE
Looks very nice!

### ISSUE THREAD

**Issue by tyeeman** [mdwhatcott/huguinho#4]
Yes, I would like to try it. I love the index page and all the tags on your site. I'm on Windows so can I just do the "go install" for now?

Tried installing but got error - 
```
go install github.com/mdwhatcott/huguinho@latest
go: downloading github.com/mdwhatcott/huguinho v0.6.2
go install: github.com/mdwhatcott/huguinho@latest: module github.com/mdwhatcott/huguinho@latest found (v0.6.2), but does not contain package github.com/mdwhatcott/huguinho
```
Any tips to install?

**Comment by mdwhatcott** [comment]
Sorry, I really should add more detail to the readme (but I never imagined anyone else would want to use this). The `makefile` reveals how I install the tool:

    go install -ldflags="-X 'main.Version=$(VERSION)'" github.com/mdwhatcott/huguinho/cmd/...

So, you could just run `go install github.com/mdwhatcott/huguinho/cmd/...`, or you could clone the repo and run `make install`.

**Comment by tyeeman** [comment]
Thanks. I will try. What does the 3 dots mean after cmd/...?
Do I have to put a number where $(VERSION) is?

**Comment by mdwhatcott** [comment]
@tyeeman - Yeah, you'll need go 1.18 to work with this code. I'm actually not even sure anymore how to install a command in a subdirectory without just cloning the repo. 

I just pushed a commit with an expanded [readme](https://github.com/mdwhatcott/huguinho/blob/main/README.md) and an [example site](https://github.com/mdwhatcott/huguinho/tree/main/example-site) you can play with. It uses the same boilerplate I (currently) use for my site. Feel free to fork and modify for your own purposes.

Please understand the I created this repo for my own website and I do tweak its behavior from time to time. In the long term I highly recommend making your own fork of the project (if you approve of the way it currently works), or creating your own static site generator from scratch that meets your needs. Good luck!

**Comment by tyeeman** [comment]
Thanks, just saw your added instructions and trying it now. Much appreciated.

**Comment by mdwhatcott** [comment]
Closing until further notice...
