### ISSUE TITLE
Copy image folder to root

### ISSUE THREAD

**Issue by tyeeman** [mdwhatcott/huguinho#5]
Seems to be running fine except I need an image folder copied to the root of the site. It seems to not do that or do I have my image folder in the wrong location (site/content/images)?

Update - I ran the non-dev version and copied my images folder into the rendered folder and it seems to not be erased after rebuilding. I guess that will work ok. In the dev version as mentioned above it did not work. I guess that's how you coded it and maybe you don't need images?

**Comment by mdwhatcott** [comment]
I've never worried about images...
