### ISSUE TITLE
How to create page like "about"

### ISSUE THREAD

**Issue by tyeeman** [mdwhatcott/huguinho#7]
I'm enjoying customizing huguinho. I just went to make a page like the "about" page without adding any topic or intro in the metadata. When it builds, it lists that supposed page as a post on the front page listing of all posts. Did I miss something in the metadata area to tell huguinho it's a page instead of a post?

**Comment by mdwhatcott** [comment]
The other bit of sorcery there is to set the date to `2000-01-01` (or some other value you want to use) in the front-matter of the article/page and then filter on that value in the templates.

See the example "about" page for usage of the `2000-01-01` date value:

https://github.com/mdwhatcott/huguinho/blob/main/example-site/content/about.md

Also see the example templates for examples of filtering on the above date to hide/show certain content:

https://github.com/mdwhatcott/huguinho/blob/main/example-site/templates/article.tmpl#L15

There are definitely different ways to do this..

**Comment by tyeeman** [comment]
Got it thanks! Works for me!
